### ISSUE TITLE
Exception thrown when calling getTorrentStatus on a non-existent hash

### ISSUE THREAD

**Issue by mitchellhuang** [TypeCtrl/deluge#23]
```
const status = await deluge.getTorrentStatus(HASH_THAT_DOES_NOT_EXIST);
```

The above will hang for `timeout` ms and then throw:

```
Timeout awaiting 'request' for 1000ms
```

Is there anyway we can get this to return null instantly or throw instantly? Surely the deluge web API doesn't just hang when requesting a non-existent torrent? Lol I hope not.

**Comment by mitchellhuang** [comment]
Btw it's similar for other methods like `getTorrentFiles`, etc

**Comment by scttcper** [comment]
@mitchellhuang deluge 2.x seems to respond correctly and quickly. added an error if it returns without the torrent data.

**Comment by scttcper** [comment]
looks like there's other issues with deluge 2 though

**Comment by mitchellhuang** [comment]
Interesting - I'll poke around on 2.x. I'm running 1.3.x rn. What are the issues? Major ones?

**Comment by scttcper** [comment]
just the api responses don't match the types, looks like some good improvements though
